#!/bin/bash -ue
echo -e S002-wR2-AAVS1-2-TR1'	'GCCATGACAACTGGGTGGAA'	'CTCACCTCTCCAAAGCTGcccatctggaggaggcgggagggagctacgagggccaagagcatgaggtcatggaaactcgggctgtgaaggggccgcacgtgccctgggaacgggatgaactcggctcgtttatttccacccagttgtcatggcgataggggaggggggcaaggAGAGCAATGGGCCTTTC
