#!/bin/bash -ue
echo -e S004-wR4-AAVS1-2-TR1'	'GCCATGACAACTGGGTGGAA'	'CTCACCTCTCCAAAGCTGcccatctggaggaggcgggagggagctacgagggccaagagcatgaggtcatggaaactcgggctgtgaaggggccgcacgtgccctgggaacgggatgaactcggctcgtttatttccacccagttgtcatggcgataggggaggggggcaaggAGAGCAATGGGCCTTTC
