#!/bin/bash -ue
echo -e S003-wR3-AAVS1-2-TR1'	'GCCATGACAACTGGGTGGAA'	'CTCACCTCTCCAAAGCTGcccatctggaggaggcgggagggagctacgagggccaagagcatgaggtcatggaaactcgggctgtgaaggggccgcacgtgccctgggaacgggatgaactcggctcgtttatttccacccagttgtcatggcgataggggaggggggcaaggAGAGCAATGGGCCTTTC
