#!/bin/bash -ue
echo -e S001-wR1-AAVS1-2-TR1'	'GCCATGACAACTGGGTGGAA'	'CTCACCTCTCCAAAGCTGcccatctggaggaggcgggagggagctacgagggccaagagcatgaggtcatggaaactcgggctgtgaaggggccgcacgtgccctgggaacgggatgaactcggctcgtttatttccacccagttgtcatggcgataggggaggggggcaaggAGAGCAATGGGCCTTTC
